# Generated by Django 4.1.7 on 2023-03-31 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_users_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colours',
            fields=[
                ('colour_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('colour_name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'colours',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Diler',
            fields=[
                ('diler_id', models.AutoField(primary_key=True, serialize=False)),
                ('diler_name', models.CharField(max_length=30)),
                ('is_related', models.BooleanField()),
            ],
            options={
                'db_table': 'diler',
            },
        ),
    ]
