# Generated by Django 4.1.7 on 2023-04-01 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_colours_diler'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.FloatField(max_length=20)),
                ('height', models.FloatField(max_length=20)),
                ('depth', models.FloatField(max_length=20)),
                ('colour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.colours')),
            ],
            options={
                'db_table': 'furniture',
            },
        ),
        migrations.CreateModel(
            name='Sofa',
            fields=[
                ('self_id', models.AutoField(primary_key=True, serialize=False)),
                ('num_seats', models.IntegerField()),
                ('expand', models.BooleanField()),
                ('corner', models.BooleanField()),
                ('fur_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.furniture')),
            ],
            options={
                'db_table': 'sofa',
            },
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('ship_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ship_date', models.DateField()),
                ('weigth', models.FloatField(max_length=30)),
                ('diler_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.diler')),
            ],
            options={
                'db_table': 'shipment',
            },
        ),
        migrations.AddField(
            model_name='furniture',
            name='ship_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.shipment'),
        ),
    ]
