# Generated by Django 4.1.7 on 2023-04-01 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_furniture_sofa_shipment_furniture_ship_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wardrobe',
            fields=[
                ('self_id', models.AutoField(primary_key=True, serialize=False)),
                ('num_shelfs', models.IntegerField()),
                ('fur_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.furniture')),
            ],
            options={
                'db_table': 'wardrobe',
            },
        ),
        migrations.CreateModel(
            name='Stol',
            fields=[
                ('self_id', models.AutoField(primary_key=True, serialize=False)),
                ('expand', models.BooleanField()),
                ('fur_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.furniture')),
            ],
            options={
                'db_table': 'stol',
            },
        ),
    ]
