# Generated by Django 4.1.7 on 2023-04-01 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_wardrobe_stol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField()),
                ('order_cost', models.FloatField(max_length=15)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service.users')),
            ],
            options={
                'db_table': 'orders',
            },
        ),
    ]
