# Generated by Django 4.1.7 on 2023-04-02 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colours',
            options={},
        ),
        migrations.RenameField(
            model_name='furniture',
            old_name='colour_id',
            new_name='colour',
        ),
        migrations.RenameField(
            model_name='furniture',
            old_name='ship_name',
            new_name='ship',
        ),
        migrations.RenameField(
            model_name='orders',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='diler_id',
            new_name='diler',
        ),
        migrations.RenameField(
            model_name='shipment',
            old_name='weigth',
            new_name='weight',
        ),
        migrations.RenameField(
            model_name='sofa',
            old_name='fur_id',
            new_name='fur',
        ),
        migrations.RenameField(
            model_name='stol',
            old_name='fur_id',
            new_name='fur',
        ),
        migrations.RenameField(
            model_name='wardrobe',
            old_name='fur_id',
            new_name='fur',
        ),
    ]
